import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { Outfit } from "next/font/google";  // Replace Inter import

import { type Metadata } from "next";
import { Navbar } from "@/components/layout/navbar"; // Import the Navbar component
import { Footer } from "@/components/layout/footer";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const outfit = Outfit({ 
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-outfit",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${outfit.variable}`}>
      <body className={`${GeistSans.className}`}>
        {children}
      </body>
    </html>
  );
}