import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { Inter } from "next/font/google";  // Replace Geist import

import { type Metadata } from "next";
import { Navbar } from "@/components/layout/navbar"; // Import the Navbar component
import { Footer } from "@/components/layout/footer";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });  // Initialize Inter


export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${inter.variable}`}> 
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}